# -- Main Menu --

[[main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[main]]
  name = "文章"
  pageRef = "posts"
  weight = 20

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/will-last"
  weight = 200

# -- Footer Menu --

[[footer]]
  name = "标签"
  pageRef = "tags"
  weight = 10

[[footer]]
  name = "作者"
  pageRef = "authors"
  weight = 20